apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
      - name: django
        image: ade8850/django-bluegreen-demo:pre8
        env:
        - name: DEBUG
          value: "0"
        envFrom:
        - secretRef:
            name: django-secrets
        - configMapRef:
            name: config-django
---

apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
 name: django
spec:
 subject:
   apiVersion: apps/v1
   kind: Deployment
   selector:
     matchLabels:
       serving.knative.dev/service: django
 sink:
   ref:
     apiVersion: eventing.knative.dev/v1
     kind: Broker
     name: default

