apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: procevents-store-django
spec:
  broker: procevents
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: procevents-store-django