apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: krules-ns-sugar
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
          - name: ruleset
            image: ade8850/krules-ns-sugar:0.1
