apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ns-sugar-ns-update
spec:
  broker: k8s-events
  filter:
    attributes:
      type: dev.knative.apiserver.resource.update
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: krules-ns-sugar