FROM {{ image_base }}

ADD requirements.txt /app/requirements-django-base.txt

RUN apk add --no-cache --virtual .build-deps g++ python3-dev openssl-dev build-base libffi-dev && \
    pip3 install --upgrade pip setuptools && \
    CRYPTOGRAPHY_DONT_BUILD_RUST=1 pip3 install --no-cache-dir -r /app/requirements-django-base.txt && \
    apk del .build-deps

{% if supports_postgres %}
RUN apk add --no-cache --virtual .build-deps g++ python3-dev postgresql-dev build-base libffi-dev && \
    apk add --no-cache --update python3 libpq && \
    pip3 install --upgrade pip setuptools && \
    pip3 install --no-cache-dir psycopg2==2.8.6 && \
    apk del .build-deps
{% endif %}

{% if supports_mysql %}

RUN apk add --virtual .build-deps mariadb-dev build-base python3-dev && \
    pip3 install --no-cache-dir mysqlclient==2.0.3 django-mysql==3.11.1 && \
    apk del .build-deps && apk add --no-cache mariadb-connector-c
{% endif %}

{%  if supports_redis %}
RUN pip3 install --no-cache-dir redis==3.5.3
{%  endif %}

WORKDIR /app

RUN django-admin startproject {{ site_name }} .

ADD site/asgi.py /app/{{ site_name }}/
ADD site/settings.py /app/{{ site_name }}
ADD site/settings_base.py /app/{{ site_name }}
ADD site/urls.py /app/{{ site_name }}

ENV CONFIGURATION_KEY {{ configuration_key }}
ENV DJANGO_SETTINGS_MODULE {{ site_name }}.settings

ENV SITE_NAME={{ site_name }}

ADD django_run.sh /app/
RUN chmod +x django_run.sh
CMD ["/app/django_run.sh"]
