FROM {{ image_base }}

ADD requirements.txt /app/requirements-django-base.txt

RUN CRYPTOGRAPHY_DONT_BUILD_RUST=1 pip3 install --no-cache-dir -r /app/requirements-django-base.txt

{% if supports_postgres %}
RUN pip3 install --no-cache-dir psycopg2-binary
{% endif %}

{% if supports_mysql %}
RUN apt update && apt install -y libmariadb-dev g++ && pip3 install mysqlclient && apt remove -y libmariadb-dev g++
{% endif %}

{%  if supports_redis %}
RUN pip3 install --no-cache-dir redis
{%  endif %}

WORKDIR /app

RUN django-admin startproject {{ site_name }} .

ADD site/asgi.py /app/{{ site_name }}/
ADD site/settings.py /app/{{ site_name }}
ADD site/settings_base.py /app/{{ site_name }}
ADD site/urls.py /app/{{ site_name }}

ENV CONFIGURATION_KEY {{ configuration_key }}
ENV DJANGO_SETTINGS_MODULE {{ site_name }}.settings

ENV SITE_NAME={{ site_name }}

ADD django_run.sh /app/
RUN chmod +x django_run.sh
CMD ["/app/django_run.sh"]
