FROM {{ image_base }}

ADD requirements.txt /app/requirements-django-base.txt

RUN apk add --no-cache --virtual .build-deps g++ python3-dev openssl-dev build-base libffi-dev && \
    pip3 install --upgrade pip setuptools && \
    CRYPTOGRAPHY_DONT_BUILD_RUST=1 pip3 install --no-cache-dir -r /app/requirements-django-base.txt && \
    apk del .build-deps

{% if supports_postgres %}
RUN apk add --no-cache --virtual .build-deps g++ python3-dev postgresql-dev build-base libffi-dev && \
    apk add --no-cache --update python3 libpq && \
    pip3 install --upgrade pip setuptools && \
    pip3 install --no-cache-dir psycopg2==2.8.6 && \
    apk del .build-deps
{% endif %}

{% if supports_mysql %}
{#(1/11) Installing pkgconf (1.6.3-r0)
(2/11) Installing openssl-dev (1.1.1k-r0)
(3/11) Installing zlib-dev (1.2.11-r3)
(4/11) Installing mariadb-connector-c (3.1.6-r1)
(5/11) Installing mariadb-connector-c-dev (3.1.6-r1)
(6/11) Installing mariadb-common (10.4.18-r0)
(7/11) Installing libaio (0.3.112-r1)
(8/11) Installing pcre (8.43-r1)
(9/11) Installing mariadb-embedded (10.4.18-r0)
(10/11) Installing mariadb-dev (10.4.18-r0)
(11/11) Installing python3-dev (3.8.10-r0)#}

RUN apk add --virtual .build-deps mariadb-dev build-base python3-dev && \
    pip3 install --no-cache-dir mysqlclient>=2.0.3 django-mysql>=3.11.1 && \
    apk del .build-deps && apk add --no-cache mariadb-connector-c
{% endif %}

{%  if supports_redis %}
RUN pip3 install --no-cache-dir redis>=3.5.3
{%  endif %}


WORKDIR /app

RUN django-admin startproject {{ site_name }} .

ADD site/asgi.py /app/{{ site_name }}/
ADD site/settings.py /app/{{ site_name }}
ADD site/urls.py /app/{{ site_name }}

ENV CONFIGURATION_KEY {{ configuration_key }}
ENV DJANGO_SETTINGS_MODULE {{ site_name }}.settings

RUN python3 manage.py collectstatic --noinput

CMD ["daphne", "-p 8080", "{{ site_name }}.asgi:application"]
