FROM {{ image_base }}
MAINTAINER Airspot <info@airspot.tech>

RUN pip3 install --no-cache-dir python-dateutil gunicorn {% if release_version %}\
{% for lib in krules_libs %}
 && pip3 install --no-cache-dir {{ lib }}=={{ release_version }} {% if not loop.last %}\{%  endif %}

{% endfor %}
{% else %}{# no release version (develop) #}
{% for lib in dev_requirements %}

RUN pip3 install --no-cache-dir {{ lib }} {% if not loop.last %}\{%  endif %}
{% endfor %}

ADD .build/.krules-libs /.krules-libs
{% for lib in krules_libs %}
RUN cd /.krules-libs/{{ lib }} && pip3 install --upgrade --no-cache-dir .
{% endfor %}
{% endif %}

ADD ./app /app

ENV PYTHONPATH /app
WORKDIR /app

RUN pip install uvicorn[standard]==0.17.6

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
