FROM alpine:3.11.6
MAINTAINER Airspot <info@airspot.tech>

RUN apk add --no-cache --virtual .build-deps g++ python3-dev && \
    apk add --no-cache build-base && \
    apk add --no-cache --update python3 && \
    pip3 install --upgrade pip setuptools

RUN pip3 install --no-cache-dir python-dateutil gunicorn {% if release_version %}\{%  endif %}

{% if release_version %}
{% for lib in krules_libs %}
pip3 install --no-cache-dir {{ lib }}=={{ release_version }} {% if not loop.last %}\{%  endif %}

{% endfor %}
RUN apk del .build-deps
{% else %}

{% for lib in dev_requirements %}
RUN pip3 install --no-cache-dir {{ lib }} {% if not loop.last %}\{%  endif %}
{% endfor %}

ADD .krules-libs krules-libs
{% for lib in krules_libs %}
RUN cd krules-libs/{{ lib }} && python3 setup.py develop

{% endfor %}
{% endif %}

ADD ./app /app

ENV PYTHONPATH /app
ENV FLASK_APP /app/main.py
ENV FLASK_ENV production
WORKDIR /app

CMD exec gunicorn --bind :8080 --workers 1 --threads 8 main:app

