apiVersion: sources.knative.dev/v1alpha2
kind: ApiServerSource
metadata:
  name: apiserversource
spec:
  serviceAccountName: lab-serviceaccount
  mode: Resource
  resources:
    - apiVersion: serving.knative.dev/v1alpha1
      kind: Configuration
    - apiVersion: serving.knative.dev/v1alpha1
      kind: Route
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: k8s-subscriber
---
