apiVersion: v1
kind: Namespace
metadata:
  name: krules-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configurationproviders.krules.airspot.dev
spec:
  group: krules.airspot.dev
  names:
    kind: ConfigurationProvider
    plural: configurationproviders
    shortNames:
    - configprovider
    - cfgprovider
    - cfgprov
    - cfgp
    singular: configurationprovider
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.applied_to
      name: APPLIES
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            anyOf:
            - required:
              - key
              - appliesTo
              - data
            - required:
              - key
              - appliesTo
              - container
            - required:
              - key
              - appliesTo
              - extraVolumes
            properties:
              appliesTo:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              container:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              data:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              extraVolumes:
                items:
                  oneOf:
                  - required:
                    - name
                    - secret
                  - required:
                    - name
                    - configMap
                  properties:
                    configMap:
                      properties:
                        name:
                          type: string
                      type: object
                    name:
                      type: string
                    secret:
                      properties:
                        secretName:
                          type: string
                      type: object
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array
              key:
                type: string
            type: object
          status:
            properties:
              applied_to:
                type: string
            type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krules-controller
  namespace: krules-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: krules-watcher-serviceaccount
  namespace: krules-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krules-controller
rules:
- apiGroups:
  - eventing.knative.dev
  - serving.knative.dev
  - sources.knative.dev
  resources:
  - brokers
  - triggers
  - services
  - apiserversources
  verbs:
  - list
  - get
  - create
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  - rbac.authorization.k8s.io
  resources:
  - serviceaccounts
  - roles
  - rolebindings
  verbs:
  - list
  - get
  - create
  - delete
- apiGroups:
  - krules.airspot.dev
  resources:
  - configurationproviders
  - configurationproviders/status
  verbs:
  - list
  - get
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
  - create
  - delete
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krules-watch-namespace
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krules-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krules-controller
subjects:
- kind: ServiceAccount
  name: krules-controller
  namespace: krules-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krules-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krules-watch-namespace
subjects:
- kind: ServiceAccount
  name: krules-watcher-serviceaccount
  namespace: krules-system
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    krules.airspot.dev/type: ruleset
    serving.knative.dev/visibility: cluster-local
  name: apiserversource-subscriber
  namespace: krules-system
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
      - image: gcr.io/airspot/apiserversource-subscriber:0.8.2
        name: ruleset
      serviceAccountName: krules-controller
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    krules.airspot.dev/type: ruleset
    serving.knative.dev/visibility: cluster-local
  name: configurations-helper
  namespace: krules-system
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
      - image: gcr.io/airspot/configurations-helper:0.8.1
        name: ruleset
      serviceAccountName: krules-controller
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    krules.airspot.dev/type: ruleset
    serving.knative.dev/visibility: cluster-local
  name: krules-ns-injector
  namespace: krules-system
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
      - image: gcr.io/airspot/krules-ns-injector:0.8.2
        name: ruleset
      serviceAccountName: krules-controller
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: krules-system
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ns-sugar-ns-label-inject
  namespace: krules-system
spec:
  broker: default
  filter:
    attributes:
      kind: Namespace
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: krules-ns-injector
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-configurationprovider
  namespace: krules-system
spec:
  broker: default
  filter:
    attributes:
      kind: ConfigurationProvider
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: configurations-helper
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-injected-resource-deleted
  namespace: krules-system
spec:
  broker: default
  filter:
    attributes:
      krulesinjected: injected
      type: k8s.resource.delete
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: krules-ns-injector
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-knative-service
  namespace: krules-system
spec:
  broker: default
  filter:
    attributes:
      apiversion: serving.knative.dev/v1
      kind: Service
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: configurations-helper
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-provided-cm-deleted
  namespace: krules-system
spec:
  broker: default
  filter:
    attributes:
      kind: ConfigMap
      krulesconfig: provided
      type: k8s.resource.delete
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: configurations-helper
---
apiVersion: sources.knative.dev/v1alpha1
kind: ApiServerSource
metadata:
  name: apiserversource
  namespace: krules-system
spec:
  mode: Resource
  resources:
  - apiVersion: v1
    kind: Namespace
    labelSelector:
      matchExpressions:
      - key: krules.airspot.dev/injection
        operator: In
        values:
        - enabled
        - disabled
  serviceAccountName: krules-watcher-serviceaccount
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: apiserversource-subscriber
---
apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: apiserversource-subscriber
  namespace: krules-system
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: apiserversource-subscriber
---
apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: configurations-helper
  namespace: krules-system
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: configurations-helper
---
apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: krules-ns-injector
  namespace: krules-system
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: krules-ns-injector
