apiVersion: v1
kind: ConfigMap
metadata:
  name: config-krules-subjects-redis
data:
  config_subjects_redis.yaml: |
    url: rediss://$REDIS_USERNAME:$REDIS_PASSWORD@private-db-redis-fra1-39029-do-user-8093456-0.b.db.ondigitalocean.com:25061/1