apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lab-admin
rules:
- apiGroups: ["*"]
  resources:
    - events
    - services
    - pods
    - deployments
    - configmaps
    - configurations
    - routes
    - revisions
  verbs:
    - list
    - get
    - watch
    - create
    - delete
    - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lab-admin-binding
subjects:
- kind: ServiceAccount
  name: lab-serviceaccount
roleRef:
  kind: Role
  name: lab-admin
  apiGroup: rbac.authorization.k8s.io