apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: krules-ns-injector
  labels:
    serving.knative.dev/visibility: cluster-local
    krules.airspot.dev/type: ruleset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      serviceAccountName: krules-controller
      containers:
      - name: ruleset
        image: gcr.io/airspot/krules-ns-injector:0.8.1
        # for development only
#        env:
#          - name: K_PROCEVENTS_SINK
#            value: http://broker-ingress.knative-eventing.svc.cluster.local/krules-system/procevents
---
apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: krules-ns-injector
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: krules-ns-injector
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default