# Generated by Django 3.0.2 on 2020-10-19 07:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.CharField(max_length=255, unique=True)),
                ('env', django.contrib.postgres.fields.jsonb.JSONField()),
                ('traffic', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='customconfig',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
