# Generated by Django 3.0.2 on 2020-10-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_auto_20201019_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='traffic',
            field=models.IntegerField(default=100),
        ),
    ]
