# Generated by Django 3.0.2 on 2020-10-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_auto_20201019_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
