apiVersion: sources.knative.dev/v1alpha1
kind: ApiServerSource
metadata:
  name: apiserversource
spec:
  serviceAccountName: krules-watcher-serviceaccount
  mode: Resource
  resources:
    - apiVersion: v1
      kind: Namespace
      labelSelector:
        matchExpressions:
          - {key: krules.airspot.dev/injection, operator: In, values: [enabled, disabled]}
#        matchLabels:
#          krules.airspot.dev/injection: enabled
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: apiserversource-subscriber
---