apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: apiserversource-subscriber
  labels:
    serving.knative.dev/visibility: cluster-local
    krules.airspot.dev/type: ruleset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      serviceAccountName: krules-controller
      containers:
      - name: ruleset
        image: localhost:5000/apiserversource-subscriber@sha256:1818bfb26132f09685aa7141ebf4eaaeddf700703c64ad016feda0a592d0a083
        # for development only
#        env:
#          - name: K_PROCEVENTS_SINK
#            value: http://broker-ingress.knative-eventing.svc.cluster.local/krules-system/procevents
---
apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: apiserversource-subscriber
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: apiserversource-subscriber
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
