apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: apiserversource-subscriber
  labels:
    serving.knative.dev/visibility: cluster-local
    krules.airspot.dev/type: ruleset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      serviceAccountName: krules-controller
      containers:
      - name: ruleset
        image: gcr.io/airspot/apiserversource-subscriber:0.8.2
---
apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: apiserversource-subscriber
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: apiserversource-subscriber
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
