apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: local-apiserversource
spec:
  serviceAccountName: demo-serviceaccount
  mode: Resource
  resources:
    - apiVersion: serving.knative.dev/v1
      kind: Service
      selector:
        matchExpressions:
          - { key: krules.airspot.dev/type, operator: In, values: [ endpoint, dashboard ] }
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: k8s-subscriber
---
