# Generated by Django 3.0.2 on 2020-12-02 10:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('origin_id', models.CharField(max_length=255)),
                ('when', models.DateTimeField()),
            ],
        ),
    ]
