FROM alpine:3.11.6
MAINTAINER Airspot <info@airspot.tech>

RUN apk add --no-cache --virtual .build-deps g++ python3-dev && \
    apk add --no-cache build-base && \
    apk add --no-cache --update python3 && \
    pip3 install --upgrade pip setuptools


{% if release_version %}
RUN pip3 install --no-cache-dir krules-env=={{ release_version }}
{% else %}
ADD .krules-libs krules-libs
RUN cd /krules-libs/krules-core && python3 setup.py develop
RUN cd /krules-libs/krules-dispatcher-cloudevents && python3 setup.py develop
RUN cd /krules-libs/krules-env && python3 setup.py develop
{% endif %}

RUN apk del .build-deps