# Generated by Django 3.2.8 on 2021-10-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('krules_djangoapps_scheduler', '0003_auto_20210614_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedulerconfig',
            name='period',
            field=models.IntegerField(default=2),
        ),
    ]
