FROM {{ image_base }}

ENV CONFIGURATION_KEY {{ configuration_key }}

RUN pip install --no-cache-dir \
  django-jsoneditor==0.1.6

{%  for app in djangoapps_sources %}
ADD apps/{{ app }} /{{ app }}
RUN cd /{{ app }} && python3 /{{ app }}/setup.py develop && cd -
{% endfor %}
