FROM {{ image_base }}

ENV CONFIGURATION_KEY {{ configuration_key }}

RUN pip install --no-cache-dir \
  django-jsoneditor==0.1.6

{% if not release_version %}
ADD .djangoapps-libs /.djangoapps-libs
{%  for app in djangoapps_sources %}
RUN cd /.djangoapps-libs/{{ app }} && python3 /.djangoapps-libs/{{ app }}/setup.py develop
{% endfor %}
{% else %}
{%  for app in djangoapps_sources %}
RUN pip3 install {{ app }}=={{ release_version }}
{%  endfor %}
{%  endif %}

