apiVersion: v1
kind: ServiceAccount
metadata:
  name: krules-watcher-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krules-watch-resources
rules:
- apiGroups: [""]
  resources:
    - namespaces
  verbs:
    - list
    - get
    - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: krules-watcher
subjects:
- kind: ServiceAccount
  name: krules-watcher-serviceaccount
roleRef:
  kind: ClusterRole
  name: krules-watch-resources
  apiGroup: rbac.authorization.k8s.io
---