apiVersion: krules.airspot.dev/v1alpha1
kind: ConfigurationProvider
metadata:
  name: config-krules-slack-webhooks
spec:
  key: slack.webhooks
  appliesTo:
    configs.krules.airspot.dev/slack-webhooks: inject
  data:
    devices_channel: https://hooks.slack.com/services/$DEVICES_CHANNEL_SLUG
    errors_channel: https://hooks.slack.com/services/$ERRORS_CHANNEL_SLUG
    middleware_channel: https://hooks.slack.com/services/$MIDDLEWARE_CHANNEL_SLUG
  container:
    envFrom:
      - secretRef:
          name: slack-webhooks
