apiVersion: krules.airspot.dev/v1alpha1
kind: ConfigurationProvider
metadata:
  name: config-google-cloud-credentials
spec:
  key: google-cloud.credentials
  appliesTo:
    configs.krules.airspot.dev/google-cloud: inject
  data:
    key.json: $GOOGLE_CLOUD_KEY
  container:
    envFrom:
      - secretRef:
          name: google-cloud-key
