apiVersion: krules.airspot.dev/v1alpha1
kind: ConfigurationProvider
metadata:
  name: config-pusher-credentials
spec:
  key: pusher.credentials
  appliesTo:
    configs.krules.airspot.dev/pusher: inject
  data:
    app_id: $APP_ID
    key: $PUSHER_APIKEY
    secret: $SECRET
    cluster: $CLUSTER
    ssl: "True"
  container:
    envFrom:
      - secretRef:
          name: pusher-credentials
