apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-role
rules:
- apiGroups: ["eventing.knative.dev"]
  resources:
    - brokers
  verbs:
    - list
    - get
- apiGroups: ["serving.knative.dev"]
  resources:
    - services
  verbs:
    - list
    - get
    - create
    - update
    - patch
    - delete
    - watch
- apiGroups: [""]
  resources:
    - secrets
    - configmaps
  verbs:
    - list
    - get
    - create
    - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-rolebinding
subjects:
- kind: ServiceAccount
  name: demo-serviceaccount
roleRef:
  kind: Role
  name: demo-role
  apiGroup: rbac.authorization.k8s.io