# Generated by Django 3.2.4 on 2021-06-14 10:25

from django.db import migrations, models
import krules_djangoapps_common.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('uid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('payload', krules_djangoapps_common.fields.EmptyObjectJSONField()),
                ('origin_id', models.CharField(max_length=255)),
                ('when', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=5)),
            ],
        ),
    ]
