apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: configurations-helper
  labels:
    serving.knative.dev/visibility: cluster-local
    krules.airspot.dev/type: ruleset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      serviceAccountName: krules-controller
      containers:
      - name: ruleset
        image: localhost:5000/configurations-helper@sha256:cfe74dc10615c00b1b597eabc9922c9f046ba1f458ad32e54a586acfb1fc9770
        # for development only
#        env:
#          - name: K_SINK
#            value: http://broker-ingress.mink-system.svc.cluster.local/krules-system/default
#          - name: LOGGING_LEVEL
#            value: "10"
#          - name: CORE_LOGGING_LEVEL
#            value: "10"

---
apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: configurations-helper
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: configurations-helper
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default