FROM {{ image_base }}

ARG site_name="djsite"
ARG configuration_key="django"

RUN pip3 install --no-cache-dir Django==3.2.8

{% if use_postgresql %}
RUN pip3 install --no-cache-dir psycopg2-binary
{% endif %}

{% if use_mysql %}
RUN apt update && apt install -y libmariadb-dev g++ && pip3 install mysqlclient && apt remove -y libmariadb-dev g++
{% endif %}

{% for user_app in user_djangoapps %}
ADD .user-djangoapps/{{ user_app }} /app/{{ user_app }}
{% endfor %}


ENV SITE_NAME=${site_name}
ENV CONFIGURATION_KEY ${configuration_key}
ENV DJANGO_SETTINGS_MODULE ${site_name}.settings

ADD site/settings.py /app/${site_name}/
ADD __init__.py /app/
ADD ruleset.py /app/

