apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-resource-add
spec:
  broker: default
  filter:
    attributes:
      type: k8s.resource.add
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: django-orm-updater
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-resource-update
spec:
  broker: default
  filter:
    attributes:
      type: k8s.resource.update
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: django-orm-updater