FROM {{ image_base }}


RUN django-admin startproject {{ site_name }} .

ADD site/asgi.py /app/{{ site_name }}/
ADD site/settings.py /app/{{ site_name }}
ADD site/settings_base.py /app/{{ site_name }}
ADD site/urls.py /app/{{ site_name }}

ENV CONFIGURATION_KEY {{ configuration_key }}
ENV DJANGO_SETTINGS_MODULE {{ site_name }}.settings

ENV SITE_NAME={{ site_name }}
