apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-configurationprovider
spec:
  broker: default
  filter:
    attributes:
      kind: ConfigurationProvider
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: configurations-helper
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-provided-cm-deleted
spec:
  broker: default
  filter:
    attributes:
      kind: ConfigMap
      type: k8s.resource.delete
      krulesconfig: provided
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: configurations-helper
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: on-knative-service
spec:
  broker: default
  filter:
    attributes:
      kind: Service
      apiversion: serving.knative.dev/v1
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: configurations-helper
---
