FROM {{ image_base }}

{% if dep_libs|length %}
RUN pip3 install --no-cache-dir \
{% for lib in dep_libs %}
    {{ lib }} {% if not loop.last %}\{%  endif %}

{% endfor %}
{% endif %}

{% if release_version and krules_dep_libs|length %}
RUN pip3 install --no-cache-dir \
{% for lib in krules_dep_libs %}
    {{ lib }}=={{ release_version }} {% if not loop.last %}\{%  endif %}

{% endfor %}

{% else %}  {# no release_version #}
ADD .krules-libs /krules-libs
{% for lib in krules_dep_libs %}
RUN cd /krules-libs/{{ lib }} && python3 setup.py develop
{% endfor %}
{% endif %}

ADD /app /app
ADD .common /app

ENV PYTHONPATH /app
ENV FLASK_APP /app/main.py
ENV FLASK_ENV production
WORKDIR /app

CMD exec gunicorn \
    --certfile /run/secrets/tls/cert --keyfile /run/secrets/tls/key \
    --bind :8443 \
    --workers 1 --threads 8 main:app