#FROM gcr.io/airspot/ruleset-image-base:0.8.5
FROM lorenzocampo/ruleset-image-base:0.8.5-20210311115358

ADD ./app /app

# RUN pip install krules-subjects-storage-redis==0.8.5
# RUN pip install krules-subjects-storage-mongodb==0.8.5