# Generated by Django 3.0.2 on 2020-12-16 15:43

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('endpoint', models.URLField(default='', max_length=255)),
                ('status', models.CharField(default='UNKNOWN', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('device_class', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_manager.Fleet')),
            ],
        ),
    ]
