# Generated by Django 3.0.2 on 2020-12-17 08:48

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='data',
            new_name='provisioning_data',
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_class',
            field=models.CharField(max_length=255, verbose_name='class'),
        ),
        migrations.CreateModel(
            name='ReceivedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_manager.Device')),
            ],
        ),
    ]
