# Generated by Django 3.0.2 on 2020-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0002_auto_20201217_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiveddata',
            options={'verbose_name_plural': 'received data'},
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='status',
        ),
        migrations.AddField(
            model_name='fleet',
            name='cluster_local',
            field=models.BooleanField(default=False),
        ),
    ]
