# Generated by Django 3.0.2 on 2020-12-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0003_auto_20201218_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='dashboard',
            field=models.URLField(default='', max_length=255),
        ),
    ]
