# Generated by Django 3.0.2 on 2021-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0004_fleet_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='id',
        ),
        migrations.AlterField(
            model_name='fleet',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
