# Generated by Django 3.0.2 on 2021-01-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0005_auto_20210104_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='fleet',
            field=models.ForeignKey(db_column='fleet_name', on_delete=django.db.models.deletion.CASCADE, to='device_manager.Fleet'),
        ),
    ]
