# Generated by Django 3.0.2 on 2021-01-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0008_auto_20210105_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTrackerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('coords', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'location tracker data',
            },
        ),
        migrations.CreateModel(
            name='LocationTrackerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fleet',
            options={'verbose_name': 'fleet middleware', 'verbose_name_plural': 'fleet middleware'},
        ),
    ]
