# Generated by Django 3.0.2 on 2021-01-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0009_auto_20210111_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtrackerservice',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
