# Generated by Django 3.2.3 on 2021-06-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krules_djangoapps_procevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingevent',
            name='origin_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processingevent',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
